<style type="text/css">
.category-products .products-grid .shop-now .button {
	padding: 5px 10px !important;
}
p.close {
	font-weight: 100;
	font-family: 'Raleway', sans-serif;
}

p.required, .validation-advice {
	display: none !important;
}

.modal-content .sign-up-form {
	margin-bottom: 20px;
}

.modal-content header {
	text-transform: uppercase;
}

.modal-content .validation-failed {
	background: #ffe6e6;
}

.modal-content {
	width: 600px;
	margin: 8% auto;
}

.modal-content input[type=email], input[type=search], input[type=number], input[type=password], input[type=tel], input[type=text] {
	width: 365px;
	max-width: 45%;
	margin-top: 3px;
	height: 40px;
}

.modal-content input[type="button" i], input[type="submit" i], input[type="reset" i], input[type="file" i]::-webkit-file-upload-button, button {
	background-color: #0c5b4d;
	color: #fff;
	border-style: initial;
	border: 1px solid #0c5b4d;
}

.modal-content input[type="button" i], input[type="submit" i], input[type="reset" i], input[type="file" i]::-webkit-file-upload-button, button:hover {
	background-color: #fff;
	color: #000;
	border: 1px solid #a5a5a5;
}

.modal-content input[placeholder="Email Address"], .modal-content input[placeholder="E-postadress"] {
	max-width: 508px;
	width: 100%;
}

.modal-content input::placeholder {
	color: #a5a5a5;
}

.modal-content .buttons {
	margin-top: 40px;
}

.modal-content .buttons p {
	padding: 6px 14px;
}

textarea {
	max-width: 508px;
	margin-top: 4px;
}

.input-text {
	font-size: 14px;
	color: #a5a5a5;
	border: 1px solid #a5a5a5;
}

@media screen and (max-width: 767px) {
	.modal-content {
		width: 90%;
	}
	.modal-content input[type=email], input[type=search], input[type=number], input[type=password], input[type=tel], input[type=text] {
		width: 365px;
		max-width: 100%;
	}
	textarea {
		max-width: 365px;
	}
}
</style>