<?php
/**
 * Klarna Checkout extension
 *
 * @category    NWT
 * @package     NWT_KCO
 * @copyright   Copyright (c) 2015 Nordic Web Team ( http://nordicwebteam.se/ )
 * @license     http://nordicwebteam.se/licenses/nwtcl/1.0.txt  NWT Commercial License (NWTCL 1.0)
 * 
 *
 */

/**
 * Discount(s) wrapper template
 */
?>
<div class="nwtkco-block nwtkco-block-discount" id="nwtkco_discount">
  <div class="nwtkco-title">
    <h2><?php echo $this->__('Discount(s)') ?></h2>
  </div>
  <?php echo $this->getChildHtml(); ?>
</div>
