<?php
/**
 * Klarna Checkout extension
 *
 * @category    NWT
 * @package     NWT_KCO
 * @copyright   Copyright (c) 2015 Nordic Web Team ( http://nordicwebteam.se/ )
 * @license     http://nordicwebteam.se/licenses/nwtcl/1.0.txt  NWT Commercial License (NWTCL 1.0)
 * 
 *
 */

/**
 * HEAD js/css template
 * NOT USED (any more)
 */
?>
<script type="text/javascript">
//<![CDATA[
    Mage.Cookies.set('<?php echo Mage::helper('nwtkco')->getScreenWidthCookieName(); ?>',screen.width);
//]]
</script>
