<div class="nwt">


    <div class="logo">
        <ul>
            <li>Östermalmsgatan 21, Stockholm</li>
            <li><em>Telefon:</em>08-518 172 00</li>
            <li><em>E-Post:</em> <a target="_blank" href="http://nordicwebteam.se/om-oss/kontakt/">info@nordicwebteam.se</a></li>
        </ul>
    </div>

    <div class="about">

        <p>
            Our company <a href="http://www.nordicwebteam.se" target="_blank">Nordic Web Team</a> delivers software for Magento and other open source platforms.
            <br />We have extensive expertise in developing modules for the scandinavian market. 
            <br />Also we are working with producing complete ecommerce implementations worldwide.
            <br />Our modules always come with included installation and with minimum risk of conflicts.
            <br />We hope you will find our modules useful and feel free to ask anything about these.
        </p>
    
        <h4 class="title">Please visit us:</h4>

        <ul>
            
            <li><a href="http://www.nordicwebteam.se" target="_blank">www.nordicwebteam.se</a> (swedish site)</a></li>
            <li><a href="http://extensions.nordicwebteam.com" target="_blank">extensions.nordicwebteam.com</a> (extension store english)</li>
            <li><a href="http://www.magentocommerce.com/magento-connect/developer/nordicwebteam" target="_blank">Magento connect</a> (developer's page)</li>
        </ul>

    </div>

</div>
<script type="text/javascript">
//<![CDATA[
$$('#nav li.level0').each(function(e){e.removeClassName('active');if(e.textContent.toLowerCase().indexOf("nordic web team")>=0) {e.addClassName('active');}});
//]]>
</script>