
<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <li><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__('Login') ?></a> </li>
<?php else: ?>
<li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"><?php echo $this->__('Logout') ?></a> </li>
<li> <a href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__('My Account') ?></a> </li>
<?php endif; ?>
