<?php 
$store = Mage::app()->getStore()->getCode();
if ($store != 'cn'): ?>
<div class="social-buttons">
    <a target="_blank" href="https://facebook.com/Knut-Gadd-Stockholm-1429872257331621/" class="social facebook">
        <div class="icon-wrapper">
            <div class="icon"></div>
            <div class="overlay"></div>
        </div>
    </a>
    <a target="_blank" href="http://instagram.com/knutgadd" class="social instagram">
        <div class="icon-wrapper">
            <div class="icon"></div>
            <div class="overlay"></div>
        </div>
    </a>
    <a target="_blank" href="https://www.linkedin.com/company/knut-gadd/" class="social linkedin">
        <div class="icon-wrapper">
            <div class="icon"></div>
            <div class="overlay"></div>
        </div>
    </a>   
</div>
<?php endif; ?>